### ISSUE TITLE
`configure.ac` breaks after forking the project

### ISSUE THREAD

**Issue by vitorvas** [seamplex/feenox#13]
On line 18: `AC_INIT([feenox],feenoxversion,[jeremy@seamplex.com])`
feenox version isn't filled after a fork. The empty variable breaks the autogen process.

**Comment by vitorvas** [comment]
I just noticed that after forking it. Usually I just clone your repo and
play with it. This time was different, but didn't know the reason.
It seems you get it immediately.

I am not in a rush. Actually, I just decided to play with feenox on a
boring train journey and since I still used a beated Core2Duo from 2010 +
Fedora, I think my weird setup can be useful for testing feenox.




Em qua., 15 de mar. de 2023 às 12:01, jeremy theler <
***@***.***> escreveu:

**Comment by jeremyonscale** [comment]
Sure, please do test it. Let me know if `make check` passes.
If the fix in https://github.com/seamplex/feenox/commit/9e5dbee034208292b09c41476b96e1e6153783b0 for no tags work let's close this issue.

**Comment by gtheler** [comment]
Hey @vitorvas . Does the fix above work? If it does, let's close this issue.

**Comment by vitorvas** [comment]
Hi Jeremy. I don't remember! I think so, but I forgot to report. Now I need
to check again. I am travelling now with no computer. Please, give me a
week and will contact you.

Sorry for that.

Regards,

Vitor

**Comment by vitorvas** [comment]
Issue solved. Thanks.
